server:
  port: 8081

spring:
  application:
    name: simulation
  rabbitmq:
    addresses: localhost:5672
  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true