server:
  port: 8081
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  application:
    name: simulation
  rabbitmq:
    host: localhost
    port: 5672
    ssl:
      enabled: false
  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

logging:
  level:
    root: INFO
    dev.notenger.config: INFO # DEBUG