server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/device
    username: notenger
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  profiles:
    active: default