server:
  port: 8082

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  application:
    name: telematics
  data:
    mongodb:
      host: mongo
      port: 27017
      authentication-database: admin
      database: telematics
      username: notenger
      password: password
  rabbitmq:
    username: notenger
    host: b-06ec40b5-3776-41d0-b937-9db8ab61e3b2.mq.eu-central-1.amazonaws.com
    port: 5671
    ssl:
      enabled: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    telematics: telematics.queue
  routing-keys:
    internal-telematics: internal.telematics.routing-key

eureka:
  client:
    enabled: false