services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: notenger
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15671:15671"
      - "61613:61613"
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      - spring
  vehicle:
    image: notenger/vehicle:latest
#    container_name: vehicle
    ports:
      - "8080:8080"
    environment:
#      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vehicle
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
  simulation:
    image: notenger/simulation:latest
#    container_name: simulation
    ports:
      - "8081:8081"
    environment:
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
#      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - postgres
      - rabbitmq
  telematics:
    image: notenger/telematics:latest
#    container_name: telematics
    ports:
      - "8082:8082"
    environment:
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
#      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres: