apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
  labels:
    app: simulation
spec:
  replicas: 1
  template:
    metadata:
      name: simulation
      labels:
        app: simulation
    spec:
      hostname: simulation
      containers:
        - name: simulation
          image: public.ecr.aws/b2y2j9p6/simulation:29.08.2024.17.57.32
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
          livenessProbe:
            httpGet:
              path: /ping
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ping
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
  selector:
    matchLabels:
      app: simulation
