apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
  labels:
    app: simulation
spec:
  replicas: 1
  template:
    metadata:
      name: simulation
      labels:
        app: simulation
    spec:
      containers:
        - name: simulation
          image: amigoscode/simulation:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: simulation
