services:
#  vehicle:
#    image: notenger/vehicle:11.04.2024.08.46.32
#    container_name: vehicle
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: aws
#    networks:
#      - spring
  simulation:
    image: notenger/simulation:09.04.2024.19.49.08
    container_name: simulation
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: aws
    networks:
      - spring
    depends_on:
      - rabbitmq
  telematics:
    image: notenger/telematics:08.04.2024.12.59.39
    container_name: telematics
    ports:
      - "8082:8082"
      - "27017:27017"
    environment:
      SPRING_PROFILES_ACTIVE: aws
    networks:
      - spring
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15671:15671"
      - "61613:61613"
    networks:
      - spring

networks:
  spring:
    driver: bridge