name: CD - Deploy Api-Gateway Service

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#    paths:
#      - apigw/**

env:
  MODULE_NAME: apigw
  DOCKERHUB_REGISTRY: notenger
  DOCKERHUB_REPOSITORY: apigw
  KUBERNETES_DEPLOYMENT: k8s/minikube/services/apigw/deployment.yml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT

      - name: Build Package Push with Maven
        env:
          IMAGE_TAG: ${{ steps.build-number.outputs.BUILD_NUMBER }}
        run: |
          mvn -ntp -B verify -pl ${{ env.MODULE_NAME }} -am \
            -Ddocker.image.registry=$DOCKERHUB_REGISTRY \
            -Ddocker.image.repository=$DOCKERHUB_REPOSITORY \
            -Ddocker.image.tag=$IMAGE_TAG \
            jib:build
          echo "image=$DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the docker-compose and k8s deployment files
        env:
          IMAGE_TAG: ${{ steps.build-number.outputs.BUILD_NUMBER }}
        run: |
          sed -i -E "s_(${DOCKERHUB_REGISTRY}/${DOCKERHUB_REPOSITORY}:)([^\"']*)_\1${IMAGE_TAG}_" docker-compose.yml ${KUBERNETES_DEPLOYMENT}

      - name: Commit and push docker-compose.yml
        env:
          IMAGE_TAG: ${{ steps.build-number.outputs.BUILD_NUMBER }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docker-compose.yml ${KUBERNETES_DEPLOYMENT}
          git commit -m "Update docker-compose.yml docker image with new tag $IMAGE_TAG"
          git pull --rebase
          git push