name: CI - Build Api-Gateway and Eureka-Server Services

on:
  pull_request:
    branches:
      - main
    paths:
      - apigw/**
      - eureka-server/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'
      - name: Build and run Unit/Integration Tests with Maven
        run: | 
          mvn -ntp -B verify -pl apigw -am
          mvn -ntp -B verify -pl eureka-server -am
