apiVersion: apps/v1
kind: Deployment
metadata:
  name: telematics
  labels:
    app: telematics
spec:
  replicas: 1
  template:
    metadata:
      name: telematics
      labels:
        app: telematics
    spec:
      hostname: telematics
      containers:
        - name: telematics
          image: public.ecr.aws/b2y2j9p6/telematics:29.08.2024.19.24.50
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
          livenessProbe:
            httpGet:
              path: /ping
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ping
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
  selector:
    matchLabels:
      app: telematics
